// classify.go holds the filename- and banner-based classification rules: IsDirectiveBlock (which
// leading comment blocks are directives, not a file header), TestFileByName, and
// GeneratedByBanner.

package toc

import "strings"

// IsDirectiveBlock reports whether stripped — an already-delimiter-stripped leading comment block
// starting at the 1-based line startLine — is a directive block for lang, and must therefore be
// skipped when looking for the file header.
//
// It returns true only when every non-empty line in stripped matches a known directive form for
// lang. A block mixing a directive line with a prose line is not a directive block. Empty lines
// inside the block are ignored when deciding.
//
//   - go: a line beginning with "go:build", "+build", "go:generate", "go:embed", or "nolint", or a
//     line matching the generated-file banner (the "Code generated " prefix together with the
//     "DO NOT EDIT." suffix, per the toolchain's own convention).
//   - csharp: a line containing "<auto-generated", treated identically to Go's banner.
//   - python: a shebang, or a PEP 263 coding line matching "coding[:=]". The match is stated on the
//     already-stripped text, not on the raw source: Python callers strip with
//     StripLineComment(raw, "#"), which removes the leading "#", so a raw
//     "#!/usr/bin/env python" arrives here as "!/usr/bin/env python" — the shebang form this
//     function matches is a line beginning with "!", never one beginning with "#!". Matching "#!"
//     here would make the rule permanently unreachable, because no caller ever passes raw text.
//     Both forms are directives only on their original first-or-second physical line, which is what
//     startLine (the block's 1-based starting line) is for — a shebang-shaped line in the middle of
//     a file is prose, not a shebang.
//   - any other language: always false. Preprocessor and attribute forms ("#pragma", "#nullable",
//     "#!") are not comment nodes in the C#, TypeScript, and Rust grammars, so they never reach this
//     rule at all — do not add dead cases for them.
func IsDirectiveBlock(lang string, startLine int, stripped string) bool {
	lines := strings.Split(stripped, "\n")
	sawDirective := false
	for offset, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if !isDirectiveLine(lang, startLine+offset, trimmed) {
			return false
		}
		sawDirective = true
	}
	return sawDirective
}

// isDirectiveLine reports whether one already-stripped, non-empty line matches a known directive
// form for lang, given the line's own 1-based lineNumber within the file.
func isDirectiveLine(lang string, lineNumber int, trimmed string) bool {
	switch lang {
	case "go":
		switch {
		case strings.HasPrefix(trimmed, "go:build"),
			strings.HasPrefix(trimmed, "+build"),
			strings.HasPrefix(trimmed, "go:generate"),
			strings.HasPrefix(trimmed, "go:embed"),
			strings.HasPrefix(trimmed, "nolint"):
			return true
		default:
			return isGeneratedBanner(trimmed)
		}
	case "csharp":
		return strings.Contains(trimmed, "<auto-generated")
	case "python":
		if lineNumber > 2 {
			return false
		}
		if strings.HasPrefix(trimmed, "!") {
			return true
		}
		return strings.Contains(trimmed, "coding:") || strings.Contains(trimmed, "coding=")
	default:
		return false
	}
}

// isGeneratedBanner reports whether trimmed matches the Go toolchain's generated-file banner
// convention: a line carrying the "Code generated " prefix together with the "DO NOT EDIT." suffix.
func isGeneratedBanner(trimmed string) bool {
	return strings.HasPrefix(trimmed, "Code generated ") && strings.HasSuffix(trimmed, "DO NOT EDIT.")
}

// TestFileByName reports whether base (a file's base name) names a test file for lang, by that
// language's toolchain or framework convention rather than by mere style.
//
// A caller must never emit false for a language whose known is false — a false test flag on, say, a
// C# test file is a lie a consumer cannot distinguish from a fact, since C# test-ness lives in
// attributes or a project file, and a "Tests.cs"-shaped name is style, not a rule.
//
//   - go: known is true; isTest is the "_test.go" suffix, which the toolchain itself defines.
//   - typescript: known is true; isTest is a ".test.ts", ".test.tsx", ".spec.ts", or ".spec.tsx"
//     suffix, the jest/vitest defaults.
//   - python: known is true; isTest is a "test_" prefix or a "_test.py" suffix, pytest's defaults.
//   - csharp, rust: known is false and isTest is false.
func TestFileByName(lang, base string) (isTest, known bool) {
	switch lang {
	case "go":
		return strings.HasSuffix(base, "_test.go"), true
	case "typescript":
		for _, suffix := range []string{".test.ts", ".test.tsx", ".spec.ts", ".spec.tsx"} {
			if strings.HasSuffix(base, suffix) {
				return true, true
			}
		}
		return false, true
	case "python":
		return strings.HasPrefix(base, "test_") || strings.HasSuffix(base, "_test.py"), true
	default:
		return false, false
	}
}

// GeneratedByBanner reports whether leadingComment — a file's already-delimiter-stripped leading
// comment block — marks the file as generated, by lang's own banner convention.
//
// A caller must never emit false for a language whose known is false, for the same reason
// documented on TestFileByName. Note that being skipped as a header candidate (IsDirectiveBlock) and
// being consumed here as a generated-file marker are independent readings of the same leading
// comment block — the banner is both.
//
//   - go: known is true; generated is whether leadingComment matches the
//     "Code generated ... DO NOT EDIT." banner.
//   - csharp: known is true; generated is whether leadingComment contains "<auto-generated".
//   - python, rust: known is false.
func GeneratedByBanner(lang, leadingComment string) (generated, known bool) {
	switch lang {
	case "go":
		for _, line := range strings.Split(leadingComment, "\n") {
			if isGeneratedBanner(strings.TrimSpace(line)) {
				return true, true
			}
		}
		return false, true
	case "csharp":
		return strings.Contains(leadingComment, "<auto-generated"), true
	default:
		return false, false
	}
}
