// classify.go holds the filename- and banner-based classification rules: IsDirectiveBlock (which
// leading comment blocks are directives, not a file header), TestFileByName, and
// GeneratedByBanner.

package toc

import "strings"

// IsDirectiveBlock reports whether stripped — an already-delimiter-stripped leading comment block
// starting at the 1-based line startLine — is a directive block for lang, and must therefore be
// skipped when looking for the file header.
//
// It returns true only when every non-empty line in stripped matches a known directive form for
// lang. A block mixing a directive line with a prose line is not a directive block. Empty lines
// inside the block are ignored when deciding.
//
//   - go: a line beginning with "go:build", "+build", "go:generate", "go:embed", or "nolint", or a
//     line matching the generated-file banner (the "Code generated " prefix together with the
//     "DO NOT EDIT." suffix, per the toolchain's own convention).
//   - csharp: a line containing "<auto-generated", treated identically to Go's banner.
//   - python: a shebang, or a PEP 263 coding line matching "coding[:=]". The match is stated on the
//     already-stripped text, not on the raw source: Python callers strip with
//     StripLineComment(raw, "#"), which removes the leading "#", so a raw
//     "#!/usr/bin/env python" arrives here as "!/usr/bin/env python" — the shebang form this
//     function matches is a line beginning with "!", never one beginning with "#!". Matching "#!"
//     here would make the rule permanently unreachable, because no caller ever passes raw text.
//     Both forms are directives only on their original first-or-second physical line, which is what
//     startLine (the block's 1-based starting line) is for — a shebang-shaped line in the middle of
//     a file is prose, not a shebang.
//   - any other language: always false. Preprocessor and attribute forms ("#pragma", "#nullable",
//     "#!") are not comment nodes in the C#, TypeScript, and Rust grammars, so they never reach this
//     rule at all — do not add dead cases for them.
func IsDirectiveBlock(lang string, startLine int, stripped string) bool {
	lines := strings.Split(stripped, "\n")
	sawDirective := false
	for offset, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if !isDirectiveLine(lang, startLine+offset, trimmed) {
			return false
		}
		sawDirective = true
	}
	return sawDirective
}

// isDirectiveLine reports whether one already-stripped, non-empty line matches a known directive
// form for lang, given the line's own 1-based lineNumber within the file.
func isDirectiveLine(lang string, lineNumber int, trimmed string) bool {
	switch lang {
	case "go":
		switch {
		case strings.HasPrefix(trimmed, "go:build"),
			strings.HasPrefix(trimmed, "+build"),
			strings.HasPrefix(trimmed, "go:generate"),
			strings.HasPrefix(trimmed, "go:embed"),
			strings.HasPrefix(trimmed, "nolint"):
			return true
		default:
			return isGeneratedBanner(trimmed)
		}
	case "csharp":
		return strings.Contains(trimmed, "<auto-generated")
	case "python":
		if lineNumber > 2 {
			return false
		}
		if strings.HasPrefix(trimmed, "!") {
			return true
		}
		return strings.Contains(trimmed, "coding:") || strings.Contains(trimmed, "coding=")
	default:
		return false
	}
}

// isGeneratedBanner reports whether trimmed matches the Go toolchain's generated-file banner
// convention: a line carrying the "Code generated " prefix together with the "DO NOT EDIT." suffix.
func isGeneratedBanner(trimmed string) bool {
	return strings.HasPrefix(trimmed, "Code generated ") && strings.HasSuffix(trimmed, "DO NOT EDIT.")
}
