// classify_test.go covers IsDirectiveBlock, TestFileByName, GeneratedByBanner, and the
// Register/StrategyFor registry machinery declared in strategy.go.

package toc

import (
	"testing"

	ts "github.com/tree-sitter/go-tree-sitter"
)

func TestIsDirectiveBlock(t *testing.T) {
	tests := []struct {
		name      string
		lang      string
		startLine int
		stripped  string
		want      bool
	}{
		{
			name:      "GoBuildBlock",
			lang:      "go",
			startLine: 1,
			stripped:  "go:build linux",
			want:      true,
		},
		{
			name:      "GoGeneratedBanner",
			lang:      "go",
			startLine: 1,
			stripped:  "Code generated by mockgen. DO NOT EDIT.",
			want:      true,
		},
		{
			name:      "GoGenerateMixedWithProse",
			lang:      "go",
			startLine: 1,
			stripped:  "go:generate mockgen -source=foo.go\nThis explains what the mock is for.",
			want:      false,
		},
		{
			name:      "PythonShebangStrippedFormAtLineOne",
			lang:      "python",
			startLine: 1,
			stripped:  "!/usr/bin/env python",
			want:      true,
		},
		{
			name:      "PythonRawShebangFormNeverMatches",
			lang:      "python",
			startLine: 1,
			stripped:  "#!/usr/bin/env python",
			want:      false,
		},
		{
			name:      "BangPrefixedLineAtLineTwelveIsNotShebang",
			lang:      "python",
			startLine: 12,
			stripped:  "!not a shebang here",
			want:      false,
		},
		{
			name:      "CSharpAutoGenerated",
			lang:      "csharp",
			startLine: 1,
			stripped:  "<auto-generated>",
			want:      true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := IsDirectiveBlock(tt.lang, tt.startLine, tt.stripped)
			if got != tt.want {
				t.Errorf("IsDirectiveBlock(%q, %d, %q) = %v; want %v", tt.lang, tt.startLine, tt.stripped, got, tt.want)
			}
		})
	}
}

func TestTestFileByName(t *testing.T) {
	tests := []struct {
		name       string
		lang       string
		base       string
		wantIsTest bool
		wantKnown  bool
	}{
		{name: "GoTestSuffix", lang: "go", base: "foo_test.go", wantIsTest: true, wantKnown: true},
		{name: "GoNonTest", lang: "go", base: "foo.go", wantIsTest: false, wantKnown: true},
		{name: "TypeScriptTestSuffix", lang: "typescript", base: "foo.test.ts", wantIsTest: true, wantKnown: true},
		{name: "TypeScriptSpecSuffix", lang: "typescript", base: "foo.spec.tsx", wantIsTest: true, wantKnown: true},
		{name: "TypeScriptNonTest", lang: "typescript", base: "foo.ts", wantIsTest: false, wantKnown: true},
		{name: "PythonTestPrefix", lang: "python", base: "test_foo.py", wantIsTest: true, wantKnown: true},
		{name: "PythonTestSuffix", lang: "python", base: "foo_test.py", wantIsTest: true, wantKnown: true},
		{name: "PythonNonTest", lang: "python", base: "foo.py", wantIsTest: false, wantKnown: true},
		{name: "CSharpNameStyleIsNotARule", lang: "csharp", base: "FooTests.cs", wantIsTest: false, wantKnown: false},
		{name: "RustUnknown", lang: "rust", base: "foo_test.rs", wantIsTest: false, wantKnown: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotIsTest, gotKnown := TestFileByName(tt.lang, tt.base)
			if gotIsTest != tt.wantIsTest || gotKnown != tt.wantKnown {
				t.Errorf("TestFileByName(%q, %q) = (%v, %v); want (%v, %v)", tt.lang, tt.base, gotIsTest, gotKnown, tt.wantIsTest, tt.wantKnown)
			}
		})
	}
}

func TestGeneratedByBanner(t *testing.T) {
	tests := []struct {
		name          string
		lang          string
		comment       string
		wantGenerated bool
		wantKnown     bool
	}{
		{name: "GoBanner", lang: "go", comment: "Code generated by mockgen. DO NOT EDIT.", wantGenerated: true, wantKnown: true},
		{name: "GoNotBanner", lang: "go", comment: "Package foo does a thing.", wantGenerated: false, wantKnown: true},
		{name: "CSharpAutoGenerated", lang: "csharp", comment: "<auto-generated>\nGenerated by a tool.\n</auto-generated>", wantGenerated: true, wantKnown: true},
		{name: "CSharpNotAutoGenerated", lang: "csharp", comment: "A hand-written comment.", wantGenerated: false, wantKnown: true},
		{name: "PythonUnknown", lang: "python", comment: "Anything at all.", wantGenerated: false, wantKnown: false},
		{name: "RustUnknown", lang: "rust", comment: "Anything at all.", wantGenerated: false, wantKnown: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotGenerated, gotKnown := GeneratedByBanner(tt.lang, tt.comment)
			if gotGenerated != tt.wantGenerated || gotKnown != tt.wantKnown {
				t.Errorf("GeneratedByBanner(%q, %q) = (%v, %v); want (%v, %v)", tt.lang, tt.comment, gotGenerated, gotKnown, tt.wantGenerated, tt.wantKnown)
			}
		})
	}
}

// fakeStrategy is a minimal Strategy implementation used only to exercise Register's
// duplicate-registration panic and StrategyFor's not-found case, isolated from the real registry via
// swapRegistry.
type fakeStrategy struct{ lang string }

func (f fakeStrategy) Language() string                                 { return f.lang }
func (f fakeStrategy) Symbols(root *ts.Node, src []byte) []Symbol       { return nil }
func (f fakeStrategy) Header(root *ts.Node, src []byte) string          { return "" }
func (f fakeStrategy) Package(root *ts.Node, src []byte) string         { return "" }
func (f fakeStrategy) Generated(root *ts.Node, src []byte) (bool, bool) { return false, false }
func (f fakeStrategy) TestFile(base string) (bool, bool)                { return false, false }

func TestRegister_PanicsOnDuplicateLanguage(t *testing.T) {
	// Isolate this subtest's registration from the rest of the package's test binary: copy the
	// current registry, swap it in, and restore the original on cleanup. Without this,
	// "fakelang" would leak past this test and fail a later test asserting the exact set of
	// registered languages, since the registry has no unregister path.
	original := swapRegistry(map[string]Strategy{})
	t.Cleanup(func() { swapRegistry(original) })

	Register(fakeStrategy{lang: "fakelang"})

	defer func() {
		if r := recover(); r == nil {
			t.Error("Register did not panic on a duplicate language registration")
		}
	}()
	Register(fakeStrategy{lang: "fakelang"})
}

func TestStrategyFor_UnregisteredNameReportsFalse(t *testing.T) {
	_, ok := StrategyFor("no-such-language")
	if ok {
		t.Error("StrategyFor(\"no-such-language\") reported ok == true; want false")
	}
}
